### ISSUE TITLE
check if required packages are installed, install if not

### ISSUE THREAD

**Issue by poer-sophia** [MHH-RCUG/haybaler#11]
@colindaven I tried your new R script  with the heatmaply heatmaps a few days ago and first I got the error that the package is not installed. Of course I just installed it and then it worked but it would be good if the script would check that and install all needed packages if they are not yet installed. 

Of course code for this purpose exists in the internet . I thought I will try a few Ideas and then we take what works best?

**Comment by colindaven** [comment]
Yep, nice one, please try this. Of course, the heatmaps require R and Rscript as well, which we at least check for...

I'm working on heatmap transformations and colour schemes. 

Briefly, log2, log10 are not good (think log2(0) = -Inf) but sqrt is promising. Will send data soon for your/Lutz's comments

**Comment by poer-sophia** [comment]
@colindaven I found something that seems to work.
While trying around I also found an Error which seems to appear random but i guess its because the conda enviroment. When haybaler or  something else is activatet i get this error, if not everything works fine. Maybe you can also try this to test if this is true. 
I mean it is no Problem to deactivate the enviroments we just need to make sure that everyone knows this.  

Error in htmlwidgets::saveWidget(., file = tmp_fp, selfcontained = TRUE) :
  Saving a widget with selfcontained = TRUE requires pandoc. For details see:
https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md
Calls: heatmaply ... freduce -> withVisible -> <Anonymous> -> <Anonymous>
Execution halted

**Comment by poer-sophia** [comment]
But the sqrt and the percentize heatmaps are looking very good. Now one can actually see these patterns which are shown in the example heatmaps when samples are similar.

**Comment by colindaven** [comment]
Yeah, but I don't actually really know if percentize is useful or what it's really doing. I find sqrt more helpful than logs, as it doesn't create problems with 0 or 1. 

The log tricks of taking the log of (x+1) are bad, because we have a lot of data which is either 0 or 0-1, which are then "present" after the transformation.

Actually, what we need to do is have a large database of metagenomes, and check the distributions of values across all. Eg 10 haybaler outputs from 10 different large projects .... thats a TODO
