### ISSUE TITLE
run on haybaler output?

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/haybaler#21]
Hi @poer-sophia 

It would make sense in my mind to run the taxonomy on haybaler output (it runs well enough on the current .fa.fai input). 

What do you think ?

Going further, it would make sense to just integrate it as a method/function in haybaler itself.

cheers,
Colin

**Comment by poer-sophia** [comment]
Yes of course that makes sense. So you think it works good enough and the few species it does not work with are ok for the moment? Because I tried a few things and to get no double TaxIDs to then check the species which havent workes yet but nothing worked. I am still in the process of trying but if you think it works well enough i can first concetrate on implementing it into haybaler.

**Comment by colindaven** [comment]
Yes, it's actually very helpful. Most of those that don't work are viruses and fungi. We can remove and or ignore them. For the most part we are interested in good bacterial identification, fungi are less prevalent. I changed the script so it printed out all non-working spp/genera

and have an issue named:

metagenome crap after 2021_02 and 2020_05 refs
