### ISSUE TITLE
big heatmaps and remove sp with <=10 reads

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/haybaler#32]
Hello Sophia,

I'm getting huge PDF files with ~hundreds of taxa. Also, the R heatmaply diagrams are breaking down with errors.

The PDFs are essentially not viewable. So I really don't think we should include all species in the heatmaps. Are even species with 0 reads/RPMM etc included ? That's a bad idea, it just does not work.

Do you think a max of say, 200 species might be better instead of all_taxa? So 50, 200, and -the non-functioning - all_taxa if you like. 

It's also very difficult to even find the heatmap, since the PDF is so huge , setting the viewer to 10% zoom makes it slightly better. 

Let me know, and I'll give you some current exampls to try eg 2020_035351_icu and umwelt2020

Thanks.

**Comment by poer-sophia** [comment]
Oh yeah you are right,  all_taxa is unfortunately less usable than I hoped. 

It could be that even taxa with 0 reads/RPMM are still included. I could integrate a filter that filters out every taxa with 0 reads in all samples. 

A few days ago Ilona asked me if  we could integrate something like that but also with more reads, like "filter out everything that has less than 5 reads in every sample" or something similar.  So I could make that read limit a variable and per default just taxa with 0 reads are filtered out but if someone wants it they could change that limit.  

Or ist that maybe too much and just filter out just the ones with 0 reads is enough? I mean I already sort the csv so that the taxa with the fewest reads are at the botttom of the file so when just the 50 or 200 top taxa are used for teh heatmap the taxa with these few reads are probably not in the heatmap.

**Comment by colindaven** [comment]
Hi,
yes, plenty of options are necessary here it seems!

Yes, all 0's should be excluded completely, that makes no sense.

A minimum reads filter, as suggested by Ilona, is good, but should be optional. One of the key and best reasons to use a heatmap is to find bacteria with many reads in many samples which have 0 in another sample. This might be the most biologically relevant result. 

The heatmaps are very useful, I did a lot of recalculation yesterday and am talking through the results with Lutz today.

**Comment by colindaven** [comment]
- RPMM threshold suggested by Lutz, Joshua - 300
- Read count threshold default - 10

Then we'll have to test, test, test and get feedback from Ilona too.
