### ISSUE TITLE
haybaler taxonomy setup

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/haybaler#46]
@irosenboom 

Pytaxonkit needs dmp taxonomy files:

#setup (for _each_ user and server!
```
mkdir /home/$USER/.taxonkit
cp /mnt/ngsnfs/tools/taxdump/* /home/$USER/.taxonkit

#should show dmp files
ls /home/$USER/.taxonkit
```

**Comment by colindaven** [comment]
We should check this at the start of wochenende_postprocess

**Comment by poer-sophia** [comment]
Should we just check if the dir .taxonkit exists and if not refer to https://bioinf.shenwei.me/taxonkit/#dataset and the Users should follow the instructions on the website 
or should we even install the requirements if not? Something like:

```
if ! [ -d /home/$USER/.taxonkit ]; then
  echo "requirements for pytaxonkit not found. Installing them now"
  wget -c ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz 
  tar -zxvf taxdump.tar.gz
  mkdir -p $HOME/.taxonkit
  cp names.dmp nodes.dmp delnodes.dmp merged.dmp $HOME/.taxonkit
```

And should we really do this in postprocess or would it be better to do it in the run_haybaler_tax.sh script? Because then it would be checken even if someone uses the script outside of postprocess.

**Comment by colindaven** [comment]
We should do check it at both stages, but just attempt to recover using the `wget taxdump` as part of the `run_haybaler_tax.sh` script. 
postprocess can just print a warning. 

cheers

**Comment by colindaven** [comment]
Done by @poer-sophia with https://github.com/MHH-RCUG/haybaler/pull/68
